# -*- coding: utf-8 -*-
"""ayuda me están ahorcando D: .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wMGIyCZqj06gVNLehHvKaBaFc89xJbeF
"""

class Juego_ahorcado():
  def __init__(self, nivel):
    self.nivel = nivel
    self.intentos = 6
    self.palabra = Palabra(nivel).palabra

  def palabras_adivinadas(self):
    print("Bien hecho! Has adivinado la palabra!")
    print("Las palabras que has adivinado son: ", self.palabra)

  def jugar(self):
    palabra_oculta = ["_"] * len(self.palabra)
    letras_usadas = []

    while self.intentos > 0 and "_" in palabra_oculta:
        print("\nPalabra:", " ".join(palabra_oculta))
        letra = input("Ingresa una letra: ")

        if letra in letras_usadas:
            print("Ya usaste esa letra")
            continue

        letras_usadas.append(letra)

        if letra in self.palabra:
            for i in range(len(self.palabra)):
                if self.palabra[i] == letra:
                    palabra_oculta[i] = letra
        else:
            self.intentos -= 1
            print("Fallaste. Intentos restantes:", self.intentos)

    if "_" not in palabra_oculta:
        print("¡Ganaste!")
        return True
    else:
        print("Perdiste. La palabra era:", self.palabra)
        return False

import random

class Palabra:
    def __init__(self, nivel):
        self.nivel = nivel
        self.palabra = self.elegir_palabra()

    def elegir_palabra(self):
        if self.nivel == 1:
            palabras = ["murcielago", "basurero", "lagarto", "carro"]
        elif self.nivel == 2:
            palabras = ["flor", "word", "astronauta", "paralelepipedo"]
        elif self.nivel == 3:
            palabras = ["hipopotomonstrosesquipedaliofobia",
                        "otorrinolaringologo",
                        "hexakosioihexekontahexafobia",
                        "electroencefalografista",
                        "humuhumunukunukuapuaa"]
        else:
            print("Nivel no válido")
            return None

        return random.choice(palabras)

class Jugador(Juego_ahorcado):
  def __init__(self, nombre):
    self.nombre = nombre
    self.puntaje = 0

jugadores = []
puntuaciones = []

def menu():
    while True:
        print("\n1- Jugar\n2- Puntuación\n3- Salir")
        opcion = input("Elige: ")

        if opcion == "1":
            nombre = input("Nombre del jugador: ")
            nivel = int(input("Nivel (1-3): "))

            if nombre in jugadores:
                indice = jugadores.index(nombre)
            else:
                jugadores.append(nombre)
                puntuaciones.append(0)
                indice = len(jugadores) - 1

            juego = Juego_ahorcado(nivel)

            resultado = juego.jugar()

            if resultado:
                puntos = nivel * 10
                puntuaciones[indice] += puntos
                print(f"Ganaste {puntos} puntos!")
            else:
                print("No ganaste puntos esta vez.")

        elif opcion == "2":
            print("\n--- PUNTUACIONES ---")
            for i in range(len(jugadores)):
                print(jugadores[i], ":", puntuaciones[i])

        elif opcion == "3":
            print("Saliendo del juego...")
            break

        else:
            print("Opción inválida")

menu()